# -*- coding: utf-8 -*-
"""현민아카데미_진로성과물

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmbA_t-Zs69wfCHK33GuCXndcLMjc_Y2

#|아이리스 분석 및 인식
"""

from sklearn.datasets import load_iris
iris_dataset = load_iris()
print(iris_dataset.keys())

print(iris_dataset['feature_names'])
print(iris_dataset['data'].shape)

import pandas as pd
iris_df = pd.DataFrame(iris_dataset['data'], columns = ['sepal length', 'sepal width', 'petal length', 'petal width'])
iris_df.head()

print(iris_dataset['target_names'])
print(type(iris_dataset['target']))
print(iris_dataset['target'].shape)
print(iris_dataset['target'])

iris_df['target'] = iris_dataset['target']
iris_df#.head()

iris_df['target'].value_counts()

iris_df.info()
iris_df.describe()

import matplotlib.pyplot as plt
plt.scatter(iris_df['sepal length'], iris_df['sepal width'])
plt.show()

setosa_df = iris_df[iris_df['target'] == 0]
plt.scatter(setosa_df['sepal length'], setosa_df['sepal width'])
plt.show()

plt.scatter(iris_df['sepal length'], iris_df['sepal width'], c = iris_df.target)
plt.colorbar()
plt.show()

from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris.target

one_hot_encoding = pd.get_dummies(iris.target)
one_hot_encoding

# 한글 지원
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

#런타임 다시시작

#한글 코드 설정
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

iris = load_iris()
x = iris.data[:, :2]
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state = 10)

knn = KNeighborsClassifier()

knn.fit(x_train, y_train)

knn.score(x_test, y_test)

from tensorflow import keras
import numpy as np
seed = 7
np.random.seed(seed)

from sklearn.datasets import load_iris

iris = load_iris()
x = iris['data']
y = iris['target']
print(x[:3])